version: '2.4'
services:
  prometheus:
    image: prom/prometheus:v2.7.1
    ports: 
      - 9090:9090
    volumes:
      - ./data/prometheus:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
  node_exporter:
    image: prom/node-exporter:v0.17.0  #monitor host
    volumes:
      - type: bind
        source: /
        target: /host
        read_only: true
    ports: 
      - 9100:9100
    command:
      - --path.rootfs
      - /host