version: '3.7'
services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana #plugins
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/ #datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/ #dashboards
    networks:
      - prometheus
    deploy:
      mode: replicated
      replicas: 1
  prometheus:
    image: prom/prometheus:v2.7.1
    ports: 
      - 9090:9090
    volumes:
      - ./data/prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prometheus
    deploy:
      mode: replicated
      replicas: 1
  node_exporter:
    image: prom/node-exporter:v0.17.0  #monitor host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      # - /etc/hostname:/etc/nodename
    # ports: 
    #   - 9100:9100
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    networks:
      - prometheus
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  cadvisor:
    image: google/cadvisor
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
    ports: 
      - 8080:8080
    networks:
      - prometheus
    deploy:
      mode: replicated
      replicas: 1
  net-tools:
    image: net-tools
    command: ping 1.1.1.1
    networks:
      - prometheus
    deploy:
      mode: replicated
      replicas: 1
networks:
  prometheus:
    ipam:
      config:
      - subnet: 172.18.0.0/16