version: '3.7'
services:
  grafana:
    image: grafana/grafana
    # ports:
    #   - 3000:3000
    volumes:
      - grafana:/var/lib/grafana #plugins
      # - ./grafana/datasources:/etc/grafana/provisioning/datasources/ #datasources
      # - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/ #dashboards
    deploy:
     replicas: 1
     mode: replicated
     labels:
       - traefik.docker.network=proxy
       - traefik.port=3000
       - traefik.backend=grafana
       - traefik.frontend.headers.browserXSSFilter=true
       - traefik.frontend.headers.frameDeny=true
       - traefik.frontend.headers.contentTypeNosniff=true
       - traefik.frontend.rule=Host:grafana.customDomain.local
    networks:
      - proxy
      - prometheus
  prometheus:
    image: prom/prometheus:v2.7.1
    # ports: 
    #   - 9090:9090
    volumes:
      - prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    deploy:
     replicas: 1
     mode: replicated
     labels:
       - traefik.docker.network=proxy
       - traefik.port=9090
       - traefik.backend=prometheus
       - traefik.frontend.headers.browserXSSFilter=true
       - traefik.frontend.headers.frameDeny=true
       - traefik.frontend.headers.contentTypeNosniff=true
       - traefik.frontend.rule=Host:prometheus.customDomain.local
    networks:
      - proxy
      - prometheus
  node_exporter:
    image: prom/node-exporter:v0.17.0  #monitor host
    volumes:
      - type: bind
        source: /
        target: /host
        read_only: true
    # ports: 
    #   - 9100:9100
    command:
      - --path.rootfs
      - /host
    deploy:
     mode: global
    networks:
      - prometheus
  cadvisor:
    image: google/cadvisor
    command: -logtostderr -docker_only
    # ports:
    #   - 8100:8100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
    networks:
      - proxy
      - prometheus
    deploy:
     replicas: 1
     mode: replicated
     labels:
       - traefik.docker.network=proxy
       - traefik.port=8080
       - traefik.backend=cadvisor
       - traefik.frontend.headers.browserXSSFilter=true
       - traefik.frontend.headers.frameDeny=true
       - traefik.frontend.headers.contentTypeNosniff=true
       - traefik.frontend.rule=Host:cadvisor.customDomain.local
networks:
  proxy:
    external: true
  prometheus: {}
volumes:
  grafana:
  prometheus: