global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: 'node-exporter'
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - node_exporter:9100
  # dns_sd_configs:
  # - names:
  #   - 'tasks.cadvisor'
  #   type: 'A'
  #   port: 8080
- job_name: 'docker-metrics'
  scheme: http
  metrics_path: /metrics
  static_configs:
  - targets:
    - 172.18.0.1:9323
- job_name: 'cadvisor'
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - cadvisor:8080
  # dns_sd_configs:
  # - names:
  #   - 'node-exporter'
  #   type: 'A'
  #   port: 9100